P16-307: Use traditional logical operator instead of "and"
The usage of logical operator "and" in 815c1dde483bcea6ea700c031617b9fd1efcd13b was causing error C2065 in Windows 10 MSVC 2019 build. We decided to change to "&&" instead of adding Windows specific compiler switch.