P16-424: Do not use designated initializers which is a c++20 feature in MSVC
This clears the error C7555 (use of designated initializers requires at least '/std:c++latest') building in Windows.